blockbuster.config.comments:
    general:
        disable_teleport_playback_button: 當你潛行使用播放按鈕的時候，传送功能是否開啟？
        extra_wubs: 這個選項可能沒有作用，或者有點用？
        auto_refresh_models: 當進入 Metamorph 或 Blockbuster 的 GUI 時，自動刷新模型和皮膚？
        debug_playback_ticks: 當導演方塊錄制時，將 tick 時間寫入日誌檔案
        green_screen_sky: 將天空完全變綠，用來鍵控摳像

    model_block:
        model_block_disable_item_rendering: 是否要關閉模型方塊的物品渲染（有人想要關掉嗎？）
        
    recording:
        recording_countdown: 錄制倒計時（秒）
        recording_delay: 錄制的幀延遲
        record_unload_time: 解除安裝一個錄制需要多久？（tick）
        record_unload: 開啟自動解除安裝錄制？
        record_sync_rate: 與伺服器同步一個回放的頻率是？
        record_attack_on_swipe: 是否錄制揮手時，生物受到的傷害？
        record_commands: 是否錄制玩家鍵入的命令？
        record_chat_prefix: 將會在確切要執行的命令之前預先用的前置代號（%NAME% 通配符可用于指向演員的名稱）

    actor:
        actor_fall_damage: 演員是否會掉落傷害？
        actor_tracking_range: 演員跟蹤會多遠？需要重啟遊戲。
        actor_rendering_range: 演員多遠可見？
        actor_always_render_names: 開啟無條件渲染演員名稱
        actor_swish_swipe: 當演員揮手時是否產生刷刷聲？

    damage_control:
        damage_control: 傷害控制是否開啟
        damage_control_distance: 傷害控制效果的半徑範圍
