# Config strings
blockbuster.config:
    general:
        title: General

        load_models_on_login: Send models
        recording_delay: Recording frame skip
        camera_duration_step: Duration step
        camera_duration: Default fixture duration