# Config strings
blockbuster.config:
    general:
        title: General
        
        load_models_on_login: Send models
        clean_model_downloads: Clean model downloads
        disable_teleport_playback_button: Disable playback button teleport
    
    recording:
        title: Recording

        recording_countdown: Recording countdown
        recording_delay: Recording frame skip
        record_unload_time: Automatic record unload time
        record_unload: Automatic record unloading
        record_sync_rate: Record tick synchronization rate
        record_attack_on_swipe: Attack on swipe
    
    camera:
        title: Camera
        
        camera_duration: Default fixture duration
        camera_duration_step: Duration step
        camera_interpolate_target: Interpolate target fixtures
        camera_interpolate_target_value: Target interpolation value
        camera_spectator: Switch to specator
    
    actor:
        title: Actor
        
        actor_fall_damage: Actor fall damage
        actor_tracking_range: Actor tracking range
        actor_rendering_range: Actor rendering range
