# Config strings
blockbuster.config:
    general:
        title: 通用

        load_models_on_login: 发送模型
        clean_model_downloads: 清除模型的下载内容
        disable_teleport_playback_button: 关闭播放后瞬移功能
        extra_wubs: 附加的杂物
        auto_refresh_models: 刷新模型和皮肤

    recording:
        title: 录制

        recording_countdown: 录制倒计时
        recording_delay: 录制跳过帧
        record_unload_time: 自动卸载录制的时间
        record_unload: 自动卸载录制的
        record_sync_rate: 录制tick的同步率
        record_attack_on_swipe: 挥动手攻击
        record_commands: 录制命令

    actor:
        title: 演员

        actor_fall_damage: 演员掉落伤害
        actor_tracking_range: 演员跟踪范围
        actor_rendering_range: 演员渲染范围
        actor_always_render_names: 总是渲染演员的名称
        actor_swish_swipe: 手臂划动刷刷声

    damage_control:
        title: 伤害控制

        damage_control: 伤害控制
        damage_control_distance: 伤害距离
