blockbuster.config.comments:
    general:
        disable_teleport_playback_button: 当你蹲着使用播放按钮的时候，传送功能是否开启？
        extra_wubs: 这个选项可能没有作用，或者有点用？
        auto_refresh_models: 当进入 Metamorph 或 Blockbuster 的 GUI 时，自动刷新模型和皮肤？
        debug_playback_ticks: 当导演方块录制时，将 tick 时间写入日志文件
        green_screen_sky: 将天空完全变绿，用来键控抠像

    model_block:
        model_block_disable_culling_workaround: 是否禁用剔除变通方法

    recording:
        recording_countdown: 录制倒计时（秒）
        recording_delay: 录制的帧延迟
        record_unload_time: 卸载一个录制需要多久？（tick）
        record_unload: 开启自动卸载录制？
        record_sync_rate: 与服务器同步一个回放的频率是？
        record_attack_on_swipe: 是否录制挥手时，生物受到的伤害？
        record_commands: 是否录制玩家输入的命令？

    actor:
        actor_fall_damage: 演员是否会掉落伤害？
        actor_tracking_range: 演员跟踪会多远？需要重启游戏。
        actor_rendering_range: 演员多远可见？
        actor_always_render_names: 开启无条件渲染演员名称
        actor_swish_swipe: 当演员挥手时是否产生刷刷声？

    damage_control:
        damage_control: 伤害控制是否开启
        damage_control_distance: 伤害控制效果的半径范围
